### ISSUE TITLE
endl was not declared in the scope

### ISSUE THREAD

**Issue by tejakondury** [louisepb/TexGen#1]
Hello,

I am getting the following error while compiling the make file 

`[ 47%] Building CXX object Core/CMakeFiles/TexGenCore.dir/AdjustMeshInterference.o
In file included from /home/teja/Documents/texgen/TexGen/Core/PrecompiledHeaders.h:35:0,
                 from /home/teja/Documents/texgen/TexGen/Core/AdjustMeshInterference.cpp:20:
/home/teja/Documents/texgen/TexGen/Core/Misc.h: In function ‘void TexGen::WriteValues(std::ostream&, T&, int)’:
/home/teja/Documents/texgen/TexGen/Core/Misc.h:269:15: error: ‘endl’ was not declared in this scope
     Output << endl;`
               ^~~~
I am guessing it has something to do with writing endl as **std::endl**

**Comment by louisepb** [comment]
Hi,
I've made the change made to misc.h
Louise
