### ISSUE TITLE
wrong vtk link

### ISSUE THREAD

**Issue by bmcage** [louisepb/TexGen#12]
On the wiki, section VTK, download link is no longer active, http://texgen.sourceforge.net/index.php/Compiling_from_Source#VTK

VTK 5.10.1 can be downloaded from https://gitlab.kitware.com/vtk/vtk/tags/v5.10.1
Not sure however if master does not need 6.??? as I see a commit with vtk 6 support in it.

**Comment by bmcage** [comment]
v5.10.1 is not compiling in VS2017 ...

**Comment by bmcage** [comment]
@louisepb  
So, I converted TexGen to work with VTK 6.3.0. The required changes are in #13 
Linking with VTK dll's now working though, I need to copy those dll in the dir of TexGen. 

I am able to go over the user manual with TexGen, all seems to work.

**Comment by louisepb** [comment]
All links are now updated on wiki page
