### ISSUE TITLE
Unable to launch version 3.11.0

### ISSUE THREAD

**Issue by bollycanuk** [louisepb/TexGen#20]
After installing version 3.11.0 I am unable to launch the program

- Double clicking on the exe file shows the busy cursor for a split second, then nothing
- Running as Administrator has the same result.
- No error messages

System Information:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	F9W85N72
System Manufacturer	Dell Inc.
System Model	Latitude E7450
System Type	x64-based PC
System SKU	062E
Processor	Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz, 2594 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. A11, 3/29/2016
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.858"
User Name	AJNET\dchaplin
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.89 GB
Available Physical Memory	2.39 GB
Total Virtual Memory	11.0 GB
Available Virtual Memory	3.69 GB
Page File Space	3.13 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by louisepb** [comment]
Hi, I'm aware that there's an issue with version 3.11.0 on some machines and am trying to find the problem.  In the meantime the 64-bit Python26 version is probably the most robust and can be downloaded here: https://sourceforge.net/projects/texgen/files/texgen/3.10.0/ 
The main difference is that the libraries have been upgraded in the newer version, most of the functionality is the same. 
Louise

**Comment by bollycanuk** [comment]
I have Python 3.7 on my machine and just installed 2.7 64 bit. Now TexGen 3.11.0 works!!!!

**Comment by louisepb** [comment]
Issue solved - bundled version now adds PythonPath registry key for Python 2.7 so works even if Python not installed
