### ISSUE TITLE
Typing error in Abaqus voxel file

### ISSUE THREAD

**Issue by Chebroller** [louisepb/TexGen#21]
There is a bug in TexGen v3.10.0 (and possible in 3.11.0 - I can't run it), which happens when user exports Abaqus voxel file. There is a block in the file which contains constraint equations. One string in there has a typing error in the name of of the node set **ConstraintsDriver2**. There is an unnecessary space symbol.

![Constraints Driver2](https://user-images.githubusercontent.com/42390637/71381897-a211c200-25e6-11ea-9bf9-d1878b1cc1af.png)

Abaqus solver somehow doesn't react to this error and doesn't put any error messages. This error appears only once in the file.

**Comment by louisepb** [comment]
Hi,
Apologies for taking a while to respond - I've only just returned from the Christmas break.
Thanks for spotting this, I'm not sure how it has gone undetected for so long!
Thanks,
Louise
