### ISSUE TITLE
TexGen Capabilities

### ISSUE THREAD

**Issue by ruwea** [louisepb/TexGen#39]
Hello, 

I'm a composites research engineer and am in need of elastic properties for a UD composite. The only experimental data I have is for an 8HS composite, of the same materials, will TexGen be able to "estimate" (even if very roughly) the UD properties from a woven RVE? Just wanted to ask before I took the time to download, learn the software, and then find out that it is not capable of doing so. 

Best,
Allison

**Comment by choROPeNt** [comment]
Hello,

I think TexGen is one of the best pre-processing tools for composites, especially for woven unit cells/ RVEs. But it's not capable to compute elastic properties. You will need an FE-simulation software such as Abaqus.

In your case, if you have better knowledge about your fibres and resin, you should use some semi-empirical equations/approximations based on micro mechanics to obtain your elastic properties of your UD-Material. This is standard

You should look on that reference:
**Kuno K. U. Stellbrink**: _Micromechanics of Composities: Composite Properties of Fibre and Matrix Constituents_ - Taschenbuch, 1996, ISBN: 9781569902066

In case you want to validate your results with your experimental data. Use Texten to model your 8HS weave geometry, incorporate your UD-properties (by semi-empirical solution) in the rovings, than apply PBCs on it, solve it, compute the effective properties of your unit cell and compare it to your experimental data.

Best,
Christian

**Comment by choROPeNt** [comment]
if it should go fast, you can also try DigiMat from University of Gent. But it's proprietary, not open source

**Comment by mike-matveev** [comment]
Hi Allison,

Normally, TexGen will be used to find properties of a woven composite using properties of UD as input data. It can be done as @choROPeNt described: generate a model, do FE analysis using Abaqus, extract results. 

In your case, you can perform a series of analysis where you guess your UD properties and then change them iteratively to match your data for woven composite. It is called the inverse problem (https://en.wikipedia.org/wiki/Inverse_problem).

**Comment by ruwea** [comment]
Hi all,

Thank you for your input. Unfortunately, for the resin material we are
working with, we do not have access to it's constitutive properties. Hence
the need to work backwards somehow to the UD properties. I have Abaqus and
BSAM as FEA software to use. I think using TexGen to "guess" UD input
properties might be my best option.

Best,
Allison Ruwe

B.S. Biomedical Engineering
Wright State University
B.S. Animal Science
University of Illinois at Urbana-Champaign
