### ISSUE TITLE
 Dialog Box Too Small

### ISSUE THREAD

**Issue by sskweres** [louisepb/TexGen#53]
Hello, 

I am trying to assign matrix and yarn properties on TexGen v3.12.2, but the dialog boxes are so small that I can't even use them. Is there a way to make them bigger? Some dialog boxes have are adjustable by dragging the bottom right corner, but that is not the case with these.

Thanks

**Comment by louisepb** [comment]
Apologies for missing this.  This has been fixed and is in the master branch code.  It will be included in the next release.
