### ISSUE TITLE
Specifiy the project's license in Gituhb repository settings

### ISSUE THREAD

**Issue by unfa** [louisepb/TexGen#54]
Hi!

I found there's a GPL license text in the source code (`gpl.txt`), but the license isn't set in Repository's settings on Github, so Github doesn't display it in the usual place on the repository's main page.
It'd be great to get it set there as well so people can easily see the license at a glance :)

**Comment by louisepb** [comment]
Hi @unfa ,
Sorry to be slow picking this up. Thanks for pointing this out - the repo was transferred from an SVN repo so I clearly missed this step of the process!
Best wishes,
Louise
