### ISSUE TITLE
Documentation to compile from source is out of date for current version of texgen

### ISSUE THREAD

**Issue by nes-1** [louisepb/TexGen#57]
https://texgen.sourceforge.io/index.php/Compiling_from_Source

Documentation out of date for current version:
- I assume instead of Python 2.7, Python 3 is now required.
- Is the SWIG install still version 4.0.0
(although not for the initial build):
- What specifically should be installed from OpenCascade because the link is broken:  https://dev.opencascade.org/getocc/download
- Is version 6.3 of VTK still the version to use
- Is ver 3.0.4 of wxWidgets (wxMSW) still used (I see it is possible to get this from their github)
- Does the cpp unit test version matter?

**Comment by louisepb** [comment]
I am in the process of updating this.  There is now a file "HowToBuildTexGen.pdf" in the repo with instructions for the Python 3 version.

**Comment by louisepb** [comment]
I have now updated the documentationfor Python 39. I'm afraid that we're stuck with VTK 6.3.0 until I have time to tackle the significant changes needed to update to a newer version. I've mended the OpenCASCADE link. The current version is built with 7.0.0.
The cppunit version is 1.15.1 (I think this is the most recent one) - note that this only works for a release build.
Please let me know if I've missed anything.

**Comment by nes-1** [comment]
Thank you so much for updated documentation - it's extra clear!
The only (incredibly small) sticky points I noticed were:
P.18 When setting up the directory for the python debug, the user will need to manually create the libs folder and scripts folder. Also if the user manually builds just python 3.9 in this manner they should move the python39.dll out of the dll folder to the root with the exe, among other things...
P.23 For the wxWidgets install just downloading the correct pre-compiled binaries (developer header) may be okay (vs building from source) although it looks like the dlls may not be in the right location.
P.26 It was a little ambiguous that the wxWidgets libraries that should remain not found for the configuration/generation are only the ones indicated in the figure (the cut off files (e.g. tiff, xml) should all be able to be linked manually).

**Comment by louisepb** [comment]
Thanks for the feedback - much appreciated.  I'll try to get around to the updates soon. When it's something you're very familiar with it's easy to miss something that might catch people out.

**Comment by 10427788** [comment]
Hi, While compiling CMAKE with make command, I used to get the following error :+1: fatal error: vtkOrientationMarkerWidget.h: No such file or directory
   35 | #include "vtkOrientationMarkerWidget.h"
I used version of Texgen 3.1.10 since I am having Python 2.7, Cmake 3.22.1, and Swig 4.0.2, May I know how to resolve this error. Thanks you

**Comment by 10427788** [comment]
Hi, while trying to compile Texgen using CMake, I encountered a VTK dependency error. To resolve this issue, I tried incorporating the find_package command in the CMake list, but it is still showing the same dependency error. This installation was initiated on Ubuntu with root access. For this installation, I was using Texgen3.1.0 version because I am trying to integrate Texgen with Python2.7inhouse for my research. Could you please provide me the step by step clear explanation for building the source code on Ubuntu . Although there were given some instruction on installation of Texgen on Wikipage but it was showing some confusion especially for the part of activating the dependency software interface. Thanks in advance

**Comment by 10427788** [comment]
<pre>[ 79%] <font color="#26A269">Building C object Core/CMakeFiles/TexGenCore.dir/__/units/units.o</font>
<b>/home/pitchaip/TexGen-3.11.0/units/units.c:</b> In function ‘<b>reduceUnit</b>’:
<b>/home/pitchaip/TexGen-3.11.0/units/units.c:541:11:</b> <font color="#A347BA"><b>warning: </b></font>implicit declaration of function ‘<b>isspace</b>’ [<font color="#A347BA"><b>-Wimplicit-function-declaration</b></font>]
  541 |   while ( <font color="#A347BA"><b>isspace</b></font>(*unitString) ) unitString++;
      |           <font color="#A347BA"><b>^~~~~~~</b></font>
<b>/home/pitchaip/TexGen-3.11.0/units/units.c:38:1:</b> <font color="#2AA1B3"><b>note: </b></font>include ‘<b>&lt;ctype.h&gt;</b>’ or provide a declaration of ‘<b>isspace</b>’
   37 | #include&lt;stdlib.h&gt;
  +++ |+<font color="#26A269">#include &lt;ctype.h&gt;</font>
   38 | 
[ 79%] <font color="#26A269"><b>Linking CXX shared library ../libTexGenCore.so</b></font>
[ 79%] Built target TexGenCore
[ 80%] <font color="#26A269">Building CXX object LatinHypercube/CMakeFiles/LatinHypercube.dir/latin_random.o</font>
[ 80%] <font color="#26A269"><b>Linking CXX static library ../libLatinHypercube.a</b></font>
[ 80%] Built target LatinHypercube
[ 80%] <font color="#26A269">Building CXX object Renderer/CMakeFiles/TexGenRenderer.dir/CustomInteractorStyle.o</font>
In file included from <b>/home/pitchaip/TexGen-3.11.0/Renderer/CustomInteractorStyle.cpp:20</b>:
<b>/home/pitchaip/TexGen-3.11.0/Renderer/PrecompiledHeaders.h:35:10:</b> <font color="#C01C28"><b>fatal error: </b></font>vtkOrientationMarkerWidget.h: No such file or directory
   35 | #include <font color="#C01C28"><b>&quot;vtkOrientationMarkerWidget.h&quot;</b></font>
      |          <font color="#C01C28"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
make[2]: *** [Renderer/CMakeFiles/TexGenRenderer.dir/build.make:76: Renderer/CMakeFiles/TexGenRenderer.dir/CustomInteractorStyle.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: Renderer/CMakeFiles/TexGenRenderer.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
<font color="#26A269"><b>pitchaip@IHP-SPD-1110508</b></font>:<font color="#12488B"><b>~/TexGen-3.11.0/bin</b></font>$ 
</pre>
