### ISSUE TITLE
Python interface: import TexGen

### ISSUE THREAD

**Issue by evenrose** [louisepb/TexGen#59]
Hi, thank you for your interesting and helpful work! I have a question about how to use the Python interface. I would like to generate a lot of samples for subsequent work and try to speed up by not using the GUI. But I found that although I had installed python3.9 separately first and then installed TexGen, I still couldn't import TexGen directly when I selected this python3.9 as the interpreter in pycharm or another IDE. I would be very grateful if you have any suggestions.

**Comment by bairizhuozhuo** [comment]
你好，我有一个abaqus的插件，它使用了Python2的texgen，可以导入Texgen。但是最新的python3的texgen无法使用

**Comment by bairizhuozhuo** [comment]
你好，我有一个abaqus的插件，它使用了Python2的texgen，可以导入Texgen。但是最新的python3的texgen无法使用

**Comment by evenrose** [comment]
> 你好，我有一个abaqus的插件，它使用了Python2的texgen，可以导入Texgen。但是最新的python3的texgen无法使用

你好呀，谢谢回复，我是想利用texgen的几何生成功能，生成用于仿真CT数据集的几何模型，因此要自动化的生成很多。abaques似乎是用于有限元仿真的？请问这个插件有什么功能呢？我也想知道texgen的python接口在他的gui里是可以被调用的，在您的插件里是怎么把texgen这个包导进去的？

**Comment by bairizhuozhuo** [comment]
这个插件是用来获取纤维束的局部坐标方向的，它使用的基于python2的Texgen。我昨天在基于python3的texgen上解决了这个问题。你可以下载TexGen3.13.1不绑定python版本，然后将主目录中的dll文件全部复制到...\Python\libxtra\TexGen中。然后在python中使用sys.path.append 将...\Python\libxtra\TexGen 添加到包搜索路径就可以了

**Comment by louisepb** [comment]
Please could you keep comments to English so that we can all understand them.
Thank you, 
Louise
